"""국가별 주요 종목 및 글로벌 스프레드 매핑."""

# 섹터 정의
SECTORS = {
    "Technology":    {"ko": "기술", "color": "#7C3AED"},
    "Semiconductor": {"ko": "반도체", "color": "#2563EB"},
    "Finance":       {"ko": "금융", "color": "#0891B2"},
    "Healthcare":    {"ko": "헬스케어", "color": "#059669"},
    "Consumer":      {"ko": "소비재", "color": "#D97706"},
    "Energy":        {"ko": "에너지", "color": "#DC2626"},
    "Automotive":    {"ko": "자동차", "color": "#7C2D12"},
    "Materials":     {"ko": "소재", "color": "#4B5563"},
    "Industrials":   {"ko": "산업재", "color": "#1D4ED8"},
    "Telecom":       {"ko": "통신", "color": "#0D9488"},
    "Battery":       {"ko": "배터리", "color": "#65A30D"},
    "Defense":       {"ko": "방산", "color": "#9D174D"},
    "Real Estate":   {"ko": "부동산", "color": "#B45309"},
    "E-Commerce":    {"ko": "이커머스", "color": "#7C3AED"},
    "Media":         {"ko": "미디어", "color": "#BE185D"},
}

# 국가별 주요 종목
STOCKS_BY_COUNTRY: dict[str, list[dict]] = {
    "US": [
        {"ticker": "NVDA",  "name": "NVIDIA",        "name_ko": "엔비디아",       "sector": "Semiconductor"},
        {"ticker": "AAPL",  "name": "Apple",          "name_ko": "애플",           "sector": "Technology"},
        {"ticker": "MSFT",  "name": "Microsoft",      "name_ko": "마이크로소프트", "sector": "Technology"},
        {"ticker": "AMZN",  "name": "Amazon",         "name_ko": "아마존",         "sector": "E-Commerce"},
        {"ticker": "GOOGL", "name": "Alphabet",       "name_ko": "알파벳",         "sector": "Technology"},
        {"ticker": "META",  "name": "Meta",           "name_ko": "메타",           "sector": "Media"},
        {"ticker": "TSLA",  "name": "Tesla",          "name_ko": "테슬라",         "sector": "Automotive"},
        {"ticker": "JPM",   "name": "JPMorgan",       "name_ko": "JP모건",         "sector": "Finance"},
        {"ticker": "XOM",   "name": "ExxonMobil",     "name_ko": "엑슨모빌",       "sector": "Energy"},
        {"ticker": "UNH",   "name": "UnitedHealth",   "name_ko": "유나이티드헬스", "sector": "Healthcare"},
    ],
    "KR": [
        {"ticker": "005930.KS", "name": "Samsung Electronics", "name_ko": "삼성전자",       "sector": "Semiconductor"},
        {"ticker": "000660.KS", "name": "SK Hynix",            "name_ko": "SK하이닉스",     "sector": "Semiconductor"},
        {"ticker": "373220.KS", "name": "LG Energy Solution",  "name_ko": "LG에너지솔루션", "sector": "Battery"},
        {"ticker": "005380.KS", "name": "Hyundai Motor",       "name_ko": "현대자동차",     "sector": "Automotive"},
        {"ticker": "000270.KS", "name": "Kia",                 "name_ko": "기아",           "sector": "Automotive"},
        {"ticker": "035420.KS", "name": "NAVER",               "name_ko": "네이버",         "sector": "Technology"},
        {"ticker": "035720.KS", "name": "Kakao",               "name_ko": "카카오",         "sector": "Technology"},
        {"ticker": "207940.KS", "name": "Samsung Biologics",   "name_ko": "삼성바이오로직스","sector": "Healthcare"},
        {"ticker": "068270.KS", "name": "Celltrion",           "name_ko": "셀트리온",       "sector": "Healthcare"},
        {"ticker": "105560.KS", "name": "KB Financial",        "name_ko": "KB금융",         "sector": "Finance"},
    ],
    "JP": [
        {"ticker": "7203.T",  "name": "Toyota",    "name_ko": "도요타",    "sector": "Automotive"},
        {"ticker": "6758.T",  "name": "Sony",      "name_ko": "소니",      "sector": "Technology"},
        {"ticker": "9984.T",  "name": "SoftBank",  "name_ko": "소프트뱅크","sector": "Technology"},
        {"ticker": "7974.T",  "name": "Nintendo",  "name_ko": "닌텐도",    "sector": "Technology"},
        {"ticker": "6861.T",  "name": "Keyence",   "name_ko": "키엔스",    "sector": "Technology"},
        {"ticker": "8306.T",  "name": "MUFG",      "name_ko": "미쓰비시UFJ","sector": "Finance"},
        {"ticker": "6954.T",  "name": "Fanuc",     "name_ko": "화낙",      "sector": "Industrials"},
        {"ticker": "4502.T",  "name": "Takeda",    "name_ko": "다케다제약","sector": "Healthcare"},
        {"ticker": "9433.T",  "name": "KDDI",      "name_ko": "KDDI",      "sector": "Telecom"},
        {"ticker": "6501.T",  "name": "Hitachi",   "name_ko": "히타치",    "sector": "Industrials"},
    ],
    "DE": [
        {"ticker": "SAP.DE",  "name": "SAP",           "name_ko": "SAP",         "sector": "Technology"},
        {"ticker": "SIE.DE",  "name": "Siemens",        "name_ko": "지멘스",      "sector": "Industrials"},
        {"ticker": "ALV.DE",  "name": "Allianz",        "name_ko": "알리안츠",    "sector": "Finance"},
        {"ticker": "MBG.DE",  "name": "Mercedes-Benz",  "name_ko": "메르세데스",  "sector": "Automotive"},
        {"ticker": "BMW.DE",  "name": "BMW",            "name_ko": "BMW",         "sector": "Automotive"},
        {"ticker": "BAYN.DE", "name": "Bayer",          "name_ko": "바이엘",      "sector": "Healthcare"},
        {"ticker": "BAS.DE",  "name": "BASF",           "name_ko": "BASF",        "sector": "Materials"},
        {"ticker": "VOW3.DE", "name": "Volkswagen",     "name_ko": "폭스바겐",    "sector": "Automotive"},
        {"ticker": "DTE.DE",  "name": "Deutsche Telekom","name_ko": "도이체텔레콤","sector": "Telecom"},
        {"ticker": "EOAN.DE", "name": "E.ON",           "name_ko": "E.ON",        "sector": "Energy"},
    ],
    "GB": [
        {"ticker": "SHEL.L", "name": "Shell",        "name_ko": "쉘",         "sector": "Energy"},
        {"ticker": "AZN.L",  "name": "AstraZeneca",  "name_ko": "아스트라제네카","sector": "Healthcare"},
        {"ticker": "HSBA.L", "name": "HSBC",         "name_ko": "HSBC",       "sector": "Finance"},
        {"ticker": "BP.L",   "name": "BP",           "name_ko": "BP",         "sector": "Energy"},
        {"ticker": "ULVR.L", "name": "Unilever",     "name_ko": "유니레버",   "sector": "Consumer"},
        {"ticker": "GSK.L",  "name": "GSK",          "name_ko": "GSK",        "sector": "Healthcare"},
        {"ticker": "RIO.L",  "name": "Rio Tinto",    "name_ko": "리오틴토",   "sector": "Materials"},
        {"ticker": "LLOY.L", "name": "Lloyds",       "name_ko": "로이즈뱅크", "sector": "Finance"},
        {"ticker": "BA.L",   "name": "BAE Systems",  "name_ko": "BAE시스템즈","sector": "Defense"},
        {"ticker": "VOD.L",  "name": "Vodafone",     "name_ko": "보다폰",     "sector": "Telecom"},
    ],
    "FR": [
        {"ticker": "LVMH.PA",  "name": "LVMH",       "name_ko": "LVMH",     "sector": "Consumer"},
        {"ticker": "OR.PA",    "name": "L'Oréal",    "name_ko": "로레알",   "sector": "Consumer"},
        {"ticker": "TTE.PA",   "name": "TotalEnergies","name_ko": "토탈에너지","sector": "Energy"},
        {"ticker": "SAN.PA",   "name": "Sanofi",     "name_ko": "사노피",   "sector": "Healthcare"},
        {"ticker": "BNP.PA",   "name": "BNP Paribas","name_ko": "BNP파리바","sector": "Finance"},
        {"ticker": "AIR.PA",   "name": "Airbus",     "name_ko": "에어버스", "sector": "Industrials"},
        {"ticker": "RI.PA",    "name": "Pernod Ricard","name_ko": "페르노리카","sector": "Consumer"},
        {"ticker": "CS.PA",    "name": "AXA",        "name_ko": "AXA",      "sector": "Finance"},
        {"ticker": "MC.PA",    "name": "LVMH",       "name_ko": "모에헤네시","sector": "Consumer"},
        {"ticker": "CAP.PA",   "name": "Capgemini",  "name_ko": "캡제미나이","sector": "Technology"},
    ],
    "HK": [
        {"ticker": "0700.HK",  "name": "Tencent",       "name_ko": "텐센트",    "sector": "Technology"},
        {"ticker": "9988.HK",  "name": "Alibaba",        "name_ko": "알리바바",  "sector": "E-Commerce"},
        {"ticker": "0941.HK",  "name": "China Mobile",   "name_ko": "차이나모바일","sector": "Telecom"},
        {"ticker": "1299.HK",  "name": "AIA Group",      "name_ko": "AIA그룹",  "sector": "Finance"},
        {"ticker": "0005.HK",  "name": "HSBC",           "name_ko": "HSBC홍콩", "sector": "Finance"},
        {"ticker": "1810.HK",  "name": "Xiaomi",         "name_ko": "샤오미",   "sector": "Technology"},
        {"ticker": "9999.HK",  "name": "NetEase",        "name_ko": "넷이즈",   "sector": "Media"},
        {"ticker": "3690.HK",  "name": "Meituan",        "name_ko": "메이퇀",   "sector": "E-Commerce"},
        {"ticker": "2318.HK",  "name": "Ping An",        "name_ko": "핑안보험", "sector": "Finance"},
        {"ticker": "0388.HK",  "name": "HK Exchanges",   "name_ko": "홍콩거래소","sector": "Finance"},
    ],
    "IN": [
        {"ticker": "RELIANCE.NS",  "name": "Reliance",    "name_ko": "릴라이언스", "sector": "Energy"},
        {"ticker": "TCS.NS",       "name": "TCS",          "name_ko": "TCS",        "sector": "Technology"},
        {"ticker": "HDFCBANK.NS",  "name": "HDFC Bank",    "name_ko": "HDFC뱅크",  "sector": "Finance"},
        {"ticker": "INFY.NS",      "name": "Infosys",      "name_ko": "인포시스",  "sector": "Technology"},
        {"ticker": "ICICIBANK.NS", "name": "ICICI Bank",   "name_ko": "ICICI뱅크","sector": "Finance"},
        {"ticker": "HINDUNILVR.NS","name": "HUL",          "name_ko": "힌두스탄유니레버","sector": "Consumer"},
        {"ticker": "BAJFINANCE.NS","name": "Bajaj Finance","name_ko": "바자즈파이낸스","sector": "Finance"},
        {"ticker": "TATAMOTORS.NS","name": "Tata Motors",  "name_ko": "타타모터스","sector": "Automotive"},
        {"ticker": "WIPRO.NS",     "name": "Wipro",        "name_ko": "위프로",    "sector": "Technology"},
        {"ticker": "SUNPHARMA.NS", "name": "Sun Pharma",   "name_ko": "선파마",    "sector": "Healthcare"},
    ],
    "BR": [
        {"ticker": "VALE3.SA",  "name": "Vale",        "name_ko": "발레",     "sector": "Materials"},
        {"ticker": "PETR4.SA",  "name": "Petrobras",   "name_ko": "페트로브라스","sector": "Energy"},
        {"ticker": "ITUB4.SA",  "name": "Itaú Unibanco","name_ko": "이타우우니방코","sector": "Finance"},
        {"ticker": "BBDC4.SA",  "name": "Bradesco",    "name_ko": "브라데스쿠","sector": "Finance"},
        {"ticker": "ABEV3.SA",  "name": "Ambev",       "name_ko": "암베브",   "sector": "Consumer"},
        {"ticker": "WEGE3.SA",  "name": "WEG",         "name_ko": "WEG",      "sector": "Industrials"},
        {"ticker": "RENT3.SA",  "name": "Localiza",    "name_ko": "로칼리자", "sector": "Consumer"},
        {"ticker": "B3SA3.SA",  "name": "B3",          "name_ko": "B3거래소", "sector": "Finance"},
        {"ticker": "SUZB3.SA",  "name": "Suzano",      "name_ko": "수자노",   "sector": "Materials"},
        {"ticker": "EQTL3.SA",  "name": "Equatorial",  "name_ko": "이콰토리알","sector": "Energy"},
    ],
    "AU": [
        {"ticker": "BHP.AX",  "name": "BHP",              "name_ko": "BHP",       "sector": "Materials"},
        {"ticker": "CBA.AX",  "name": "Commonwealth Bank","name_ko": "커먼웰스뱅크","sector": "Finance"},
        {"ticker": "RIO.AX",  "name": "Rio Tinto",        "name_ko": "리오틴토",  "sector": "Materials"},
        {"ticker": "ANZ.AX",  "name": "ANZ Bank",         "name_ko": "ANZ뱅크",  "sector": "Finance"},
        {"ticker": "WBC.AX",  "name": "Westpac",          "name_ko": "웨스트팩",  "sector": "Finance"},
        {"ticker": "CSL.AX",  "name": "CSL",              "name_ko": "CSL",       "sector": "Healthcare"},
        {"ticker": "NAB.AX",  "name": "NAB",              "name_ko": "NAB",       "sector": "Finance"},
        {"ticker": "WES.AX",  "name": "Wesfarmers",       "name_ko": "웨스파머스","sector": "Consumer"},
        {"ticker": "MQG.AX",  "name": "Macquarie",        "name_ko": "맥쿼리",   "sector": "Finance"},
        {"ticker": "WDS.AX",  "name": "Woodside",         "name_ko": "우드사이드","sector": "Energy"},
    ],
    "TW": [
        {"ticker": "2330.TW", "name": "TSMC",          "name_ko": "TSMC",      "sector": "Semiconductor"},
        {"ticker": "2317.TW", "name": "Foxconn",       "name_ko": "폭스콘",   "sector": "Technology"},
        {"ticker": "2454.TW", "name": "MediaTek",      "name_ko": "미디어텍", "sector": "Semiconductor"},
        {"ticker": "2382.TW", "name": "Quanta",        "name_ko": "광다컴퓨터","sector": "Technology"},
        {"ticker": "2308.TW", "name": "Delta Electronics","name_ko": "델타전자","sector": "Industrials"},
        {"ticker": "2412.TW", "name": "Chunghwa Telecom","name_ko": "중화전신","sector": "Telecom"},
        {"ticker": "2303.TW", "name": "UMC",           "name_ko": "UMC",       "sector": "Semiconductor"},
        {"ticker": "2891.TW", "name": "CTBC Financial","name_ko": "CTBC금융", "sector": "Finance"},
        {"ticker": "2886.TW", "name": "Mega Financial","name_ko": "메가금융", "sector": "Finance"},
        {"ticker": "2002.TW", "name": "China Steel",   "name_ko": "중국강철", "sector": "Materials"},
    ],
    "CA": [
        {"ticker": "SHOP.TO", "name": "Shopify",       "name_ko": "쇼피파이", "sector": "Technology"},
        {"ticker": "RY.TO",   "name": "Royal Bank",    "name_ko": "로얄뱅크", "sector": "Finance"},
        {"ticker": "TD.TO",   "name": "TD Bank",       "name_ko": "TD뱅크",  "sector": "Finance"},
        {"ticker": "ENB.TO",  "name": "Enbridge",      "name_ko": "엔브리지","sector": "Energy"},
        {"ticker": "CNQ.TO",  "name": "Canadian Natural","name_ko": "캐나다내추럴","sector": "Energy"},
        {"ticker": "BNS.TO",  "name": "Scotiabank",    "name_ko": "스코샤뱅크","sector": "Finance"},
        {"ticker": "BMO.TO",  "name": "BMO",           "name_ko": "BMO뱅크", "sector": "Finance"},
        {"ticker": "CP.TO",   "name": "CP Railway",    "name_ko": "CP철도",  "sector": "Industrials"},
        {"ticker": "SU.TO",   "name": "Suncor Energy", "name_ko": "선코에너지","sector": "Energy"},
        {"ticker": "WCN.TO",  "name": "Waste Connections","name_ko": "웨이스트커넥션","sector": "Industrials"},
    ],
    "SG": [
        {"ticker": "D05.SI",  "name": "DBS Bank",    "name_ko": "DBS뱅크",  "sector": "Finance"},
        {"ticker": "O39.SI",  "name": "OCBC",        "name_ko": "OCBC뱅크", "sector": "Finance"},
        {"ticker": "U11.SI",  "name": "UOB",         "name_ko": "UOB뱅크",  "sector": "Finance"},
        {"ticker": "Z74.SI",  "name": "SingTel",     "name_ko": "싱텔",     "sector": "Telecom"},
        {"ticker": "C6L.SI",  "name": "Singapore Airlines","name_ko": "싱가포르항공","sector": "Industrials"},
        {"ticker": "BN4.SI",  "name": "Keppel",      "name_ko": "케펠",     "sector": "Industrials"},
        {"ticker": "U96.SI",  "name": "Sembcorp Marine","name_ko": "셈브코마린","sector": "Industrials"},
        {"ticker": "C09.SI",  "name": "City Developments","name_ko": "시티디벨롭먼트","sector": "Real Estate"},
        {"ticker": "A17U.SI", "name": "CapitaLand",  "name_ko": "캐피탈랜드","sector": "Real Estate"},
        {"ticker": "G13.SI",  "name": "Genting Singapore","name_ko": "젠팅싱가포르","sector": "Consumer"},
    ],
}

# 주요 종목 글로벌 스프레드 매핑
# 해당 종목이 오르거나 내릴 때 영향 받는 국가들
GLOBAL_SPREAD: dict[str, dict] = {
    "NVDA": {
        "desc_ko": "AI 반도체 대장주 — 글로벌 반도체 공급망 전체에 파급",
        "desc_en": "AI chip leader — ripples across global semiconductor supply chain",
        "affected": [
            {"country": "KR", "reason_ko": "HBM 납품 (삼성·SK하이닉스)", "reason_en": "HBM supply (Samsung, SK Hynix)"},
            {"country": "TW", "reason_ko": "TSMC 파운드리 수주", "reason_en": "TSMC foundry orders"},
            {"country": "JP", "reason_ko": "소재·장비 공급망", "reason_en": "Materials & equipment supply"},
            {"country": "NL", "reason_ko": "ASML 노광장비 수요", "reason_en": "ASML lithography demand"},
        ],
    },
    "AAPL": {
        "desc_ko": "글로벌 공급망 허브 — 부품 생산국 전반에 영향",
        "desc_en": "Global supply chain hub — impacts all component-producing nations",
        "affected": [
            {"country": "KR", "reason_ko": "OLED 디스플레이·메모리 납품", "reason_en": "OLED display & memory supply"},
            {"country": "TW", "reason_ko": "TSMC A시리즈 칩 생산", "reason_en": "TSMC A-series chip production"},
            {"country": "JP", "reason_ko": "카메라 모듈·부품 공급", "reason_en": "Camera module & component supply"},
            {"country": "CN", "reason_ko": "조립 생산 (폭스콘)", "reason_en": "Assembly (Foxconn)"},
        ],
    },
    "TSLA": {
        "desc_ko": "전기차 시장 선도 — 배터리·부품 공급망 파급",
        "desc_en": "EV market leader — battery & component supply chain impact",
        "affected": [
            {"country": "KR", "reason_ko": "배터리 셀 납품 (LG·삼성SDI·SK온)", "reason_en": "Battery supply (LG, Samsung SDI, SK On)"},
            {"country": "CN", "reason_ko": "상하이 기가팩토리·공급망", "reason_en": "Shanghai Gigafactory & supply chain"},
            {"country": "JP", "reason_ko": "판매 시장 + 부품", "reason_en": "Sales market + components"},
            {"country": "AU", "reason_ko": "리튬 원자재 공급", "reason_en": "Lithium raw material supply"},
        ],
    },
    "2330.TW": {
        "desc_ko": "세계 최대 파운드리 — 팹리스 반도체 전체에 영향",
        "desc_en": "World's largest foundry — impacts all fabless chip companies",
        "affected": [
            {"country": "US", "reason_ko": "애플·엔비디아·AMD 칩 생산", "reason_en": "Apple, NVIDIA, AMD chip production"},
            {"country": "KR", "reason_ko": "삼성전자 경쟁 구도", "reason_en": "Samsung competitive dynamics"},
            {"country": "NL", "reason_ko": "ASML EUV 장비 수요", "reason_en": "ASML EUV equipment demand"},
            {"country": "JP", "reason_ko": "화학·소재 공급망", "reason_en": "Chemical & material supply"},
        ],
    },
    "005930.KS": {
        "desc_ko": "글로벌 메모리·디스플레이 리더 — 반도체 업황 바로미터",
        "desc_en": "Global memory & display leader — semiconductor sector barometer",
        "affected": [
            {"country": "US", "reason_ko": "데이터센터 메모리 수요", "reason_en": "Data center memory demand"},
            {"country": "TW", "reason_ko": "파운드리 경쟁·협력", "reason_en": "Foundry competition & collaboration"},
            {"country": "JP", "reason_ko": "소재·장비 공급", "reason_en": "Materials & equipment supply"},
            {"country": "CN", "reason_ko": "스마트폰 수요 연동", "reason_en": "Smartphone demand linkage"},
        ],
    },
    "7203.T": {
        "desc_ko": "자동차 판매 1위 — 글로벌 자동차 업종 전반에 영향",
        "desc_en": "World's top automaker — impacts global automotive sector",
        "affected": [
            {"country": "US", "reason_ko": "북미 최대 판매 시장", "reason_en": "Top North American sales market"},
            {"country": "KR", "reason_ko": "현대·기아 경쟁 구도", "reason_en": "Hyundai/Kia competitive dynamics"},
            {"country": "AU", "reason_ko": "철강·알루미늄 원자재", "reason_en": "Steel & aluminum raw materials"},
            {"country": "IN", "reason_ko": "인도 생산 거점", "reason_en": "India production base"},
        ],
    },
    "XOM": {
        "desc_ko": "에너지 메이저 — 유가 연동 전 세계 에너지 섹터 파급",
        "desc_en": "Energy major — global energy sector ripple linked to oil prices",
        "affected": [
            {"country": "SA", "reason_ko": "OPEC+ 원유 수요 연동", "reason_en": "OPEC+ crude oil demand linkage"},
            {"country": "BR", "reason_ko": "페트로브라스 연동", "reason_en": "Petrobras correlation"},
            {"country": "GB", "reason_ko": "Shell·BP 섹터 동조", "reason_en": "Shell/BP sector correlation"},
            {"country": "AU", "reason_ko": "LNG 수출 가격 연동", "reason_en": "LNG export price linkage"},
        ],
    },
    "VALE3.SA": {
        "desc_ko": "철광석 최대 생산국 — 철강·소재 글로벌 공급망",
        "desc_en": "Top iron ore producer — global steel & materials supply chain",
        "affected": [
            {"country": "CN", "reason_ko": "최대 철광석 수입국", "reason_en": "Top iron ore importer"},
            {"country": "JP", "reason_ko": "신일철 등 철강 소재", "reason_en": "Nippon Steel raw materials"},
            {"country": "KR", "reason_ko": "POSCO 원료 수입", "reason_en": "POSCO raw material imports"},
            {"country": "DE", "reason_ko": "철강 소재 수입", "reason_en": "Steel material imports"},
        ],
    },
}

TICKER_TO_SPREAD = {k: v for k, v in GLOBAL_SPREAD.items()}
