"""Add stock_news and stock_metadata tables

Revision ID: 7a7adbcb34d1
Revises: 
Create Date: 2026-06-05 20:18:11.177036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a7adbcb34d1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name_ko', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=True),
    sa.Column('sector', sa.String(length=50), nullable=True),
    sa.Column('market', sa.String(length=20), nullable=False),
    sa.Column('market_cap_rank', sa.Integer(), nullable=True),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_index('idx_sector', 'stock_metadata', ['sector'], unique=False)
    op.create_index('idx_symbol', 'stock_metadata', ['symbol'], unique=False)
    op.create_table('stock_news',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('source_title', sa.Text(), nullable=False),
    sa.Column('source_domain', sa.String(length=255), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('related_symbols', sa.Text(), nullable=True),
    sa.Column('main_symbol', sa.String(length=20), nullable=True),
    sa.Column('sector', sa.String(length=50), nullable=True),
    sa.Column('summary_title', sa.Text(), nullable=True),
    sa.Column('summary_body', sa.Text(), nullable=True),
    sa.Column('ai_processed', sa.Boolean(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index('idx_stock_news_collected_at', 'stock_news', ['collected_at'], unique=False)
    op.create_index('idx_stock_news_processed', 'stock_news', ['ai_processed'], unique=False)
    op.create_index('idx_stock_news_symbol', 'stock_news', ['main_symbol'], unique=False)
    op.create_index('idx_stock_news_url', 'stock_news', ['url'], unique=False)
    op.drop_index('idx_country_movers_country_code', table_name='country_movers_snapshots')
    op.drop_index('idx_country_movers_updated_at', table_name='country_movers_snapshots')
    op.alter_column('news_articles', 'attacker_codes',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=sa.ARRAY(sa.String(length=10)),
               existing_nullable=True)
    op.alter_column('news_articles', 'victim_codes',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=sa.ARRAY(sa.String(length=10)),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('news_articles', 'victim_codes',
               existing_type=sa.ARRAY(sa.String(length=10)),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.alter_column('news_articles', 'attacker_codes',
               existing_type=sa.ARRAY(sa.String(length=10)),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.create_index('idx_country_movers_updated_at', 'country_movers_snapshots', ['updated_at'], unique=False)
    op.create_index('idx_country_movers_country_code', 'country_movers_snapshots', ['country_code'], unique=False)
    op.drop_index('idx_stock_news_url', table_name='stock_news')
    op.drop_index('idx_stock_news_symbol', table_name='stock_news')
    op.drop_index('idx_stock_news_processed', table_name='stock_news')
    op.drop_index('idx_stock_news_collected_at', table_name='stock_news')
    op.drop_table('stock_news')
    op.drop_index('idx_symbol', table_name='stock_metadata')
    op.drop_index('idx_sector', table_name='stock_metadata')
    op.drop_table('stock_metadata')
    # ### end Alembic commands ###
